//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessCore.PassportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Passport.com/", ConfigurationName="PassportServiceReference.PassportWebServiceSoap")]
    public interface PassportWebServiceSoap {
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/HelloWorld", ReplyAction="*")]
        BusinessCore.PassportServiceReference.HelloWorldResponse HelloWorld(BusinessCore.PassportServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.HelloWorldResponse> HelloWorldAsync(BusinessCore.PassportServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 GetTokenResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetToken", ReplyAction="*")]
        BusinessCore.PassportServiceReference.GetTokenResponse GetToken(BusinessCore.PassportServiceReference.GetTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetToken", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.GetTokenResponse> GetTokenAsync(BusinessCore.PassportServiceReference.GetTokenRequest request);
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/ValidateToken", ReplyAction="*")]
        BusinessCore.PassportServiceReference.ValidateTokenResponse ValidateToken(BusinessCore.PassportServiceReference.ValidateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/ValidateToken", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.ValidateTokenResponse> ValidateTokenAsync(BusinessCore.PassportServiceReference.ValidateTokenRequest request);
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetSignNameByToken", ReplyAction="*")]
        BusinessCore.PassportServiceReference.GetSignNameByTokenResponse GetSignNameByToken(BusinessCore.PassportServiceReference.GetSignNameByTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetSignNameByToken", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.GetSignNameByTokenResponse> GetSignNameByTokenAsync(BusinessCore.PassportServiceReference.GetSignNameByTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/CountCacheMember", ReplyAction="*")]
        int CountCacheMember();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/CountCacheMember", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CountCacheMemberAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BusinessCore.PassportServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BusinessCore.PassportServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.GetTokenRequestBody Body;
        
        public GetTokenRequest() {
        }
        
        public GetTokenRequest(BusinessCore.PassportServiceReference.GetTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTokenRequestBody {
        
        public GetTokenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.GetTokenResponseBody Body;
        
        public GetTokenResponse() {
        }
        
        public GetTokenResponse(BusinessCore.PassportServiceReference.GetTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class GetTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenResult;
        
        public GetTokenResponseBody() {
        }
        
        public GetTokenResponseBody(string GetTokenResult) {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateToken", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.ValidateTokenRequestBody Body;
        
        public ValidateTokenRequest() {
        }
        
        public ValidateTokenRequest(BusinessCore.PassportServiceReference.ValidateTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class ValidateTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public ValidateTokenRequestBody() {
        }
        
        public ValidateTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateTokenResponse", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.ValidateTokenResponseBody Body;
        
        public ValidateTokenResponse() {
        }
        
        public ValidateTokenResponse(BusinessCore.PassportServiceReference.ValidateTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class ValidateTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateTokenResult;
        
        public ValidateTokenResponseBody() {
        }
        
        public ValidateTokenResponseBody(bool ValidateTokenResult) {
            this.ValidateTokenResult = ValidateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignNameByTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSignNameByToken", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.GetSignNameByTokenRequestBody Body;
        
        public GetSignNameByTokenRequest() {
        }
        
        public GetSignNameByTokenRequest(BusinessCore.PassportServiceReference.GetSignNameByTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class GetSignNameByTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetSignNameByTokenRequestBody() {
        }
        
        public GetSignNameByTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignNameByTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSignNameByTokenResponse", Namespace="http://www.Passport.com/", Order=0)]
        public BusinessCore.PassportServiceReference.GetSignNameByTokenResponseBody Body;
        
        public GetSignNameByTokenResponse() {
        }
        
        public GetSignNameByTokenResponse(BusinessCore.PassportServiceReference.GetSignNameByTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class GetSignNameByTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSignNameByTokenResult;
        
        public GetSignNameByTokenResponseBody() {
        }
        
        public GetSignNameByTokenResponseBody(string GetSignNameByTokenResult) {
            this.GetSignNameByTokenResult = GetSignNameByTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PassportWebServiceSoapChannel : BusinessCore.PassportServiceReference.PassportWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassportWebServiceSoapClient : System.ServiceModel.ClientBase<BusinessCore.PassportServiceReference.PassportWebServiceSoap>, BusinessCore.PassportServiceReference.PassportWebServiceSoap {
        
        public PassportWebServiceSoapClient() {
        }
        
        public PassportWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassportWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessCore.PassportServiceReference.HelloWorldResponse BusinessCore.PassportServiceReference.PassportWebServiceSoap.HelloWorld(BusinessCore.PassportServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BusinessCore.PassportServiceReference.HelloWorldRequest inValue = new BusinessCore.PassportServiceReference.HelloWorldRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.HelloWorldRequestBody();
            BusinessCore.PassportServiceReference.HelloWorldResponse retVal = ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.HelloWorldResponse> BusinessCore.PassportServiceReference.PassportWebServiceSoap.HelloWorldAsync(BusinessCore.PassportServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.HelloWorldResponse> HelloWorldAsync() {
            BusinessCore.PassportServiceReference.HelloWorldRequest inValue = new BusinessCore.PassportServiceReference.HelloWorldRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.HelloWorldRequestBody();
            return ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessCore.PassportServiceReference.GetTokenResponse BusinessCore.PassportServiceReference.PassportWebServiceSoap.GetToken(BusinessCore.PassportServiceReference.GetTokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public string GetToken() {
            BusinessCore.PassportServiceReference.GetTokenRequest inValue = new BusinessCore.PassportServiceReference.GetTokenRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.GetTokenRequestBody();
            BusinessCore.PassportServiceReference.GetTokenResponse retVal = ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).GetToken(inValue);
            return retVal.Body.GetTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.GetTokenResponse> BusinessCore.PassportServiceReference.PassportWebServiceSoap.GetTokenAsync(BusinessCore.PassportServiceReference.GetTokenRequest request) {
            return base.Channel.GetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.GetTokenResponse> GetTokenAsync() {
            BusinessCore.PassportServiceReference.GetTokenRequest inValue = new BusinessCore.PassportServiceReference.GetTokenRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.GetTokenRequestBody();
            return ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).GetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessCore.PassportServiceReference.ValidateTokenResponse BusinessCore.PassportServiceReference.PassportWebServiceSoap.ValidateToken(BusinessCore.PassportServiceReference.ValidateTokenRequest request) {
            return base.Channel.ValidateToken(request);
        }
        
        public bool ValidateToken(string token) {
            BusinessCore.PassportServiceReference.ValidateTokenRequest inValue = new BusinessCore.PassportServiceReference.ValidateTokenRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.ValidateTokenRequestBody();
            inValue.Body.token = token;
            BusinessCore.PassportServiceReference.ValidateTokenResponse retVal = ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).ValidateToken(inValue);
            return retVal.Body.ValidateTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.ValidateTokenResponse> BusinessCore.PassportServiceReference.PassportWebServiceSoap.ValidateTokenAsync(BusinessCore.PassportServiceReference.ValidateTokenRequest request) {
            return base.Channel.ValidateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.ValidateTokenResponse> ValidateTokenAsync(string token) {
            BusinessCore.PassportServiceReference.ValidateTokenRequest inValue = new BusinessCore.PassportServiceReference.ValidateTokenRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.ValidateTokenRequestBody();
            inValue.Body.token = token;
            return ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).ValidateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessCore.PassportServiceReference.GetSignNameByTokenResponse BusinessCore.PassportServiceReference.PassportWebServiceSoap.GetSignNameByToken(BusinessCore.PassportServiceReference.GetSignNameByTokenRequest request) {
            return base.Channel.GetSignNameByToken(request);
        }
        
        public string GetSignNameByToken(string token) {
            BusinessCore.PassportServiceReference.GetSignNameByTokenRequest inValue = new BusinessCore.PassportServiceReference.GetSignNameByTokenRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.GetSignNameByTokenRequestBody();
            inValue.Body.token = token;
            BusinessCore.PassportServiceReference.GetSignNameByTokenResponse retVal = ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).GetSignNameByToken(inValue);
            return retVal.Body.GetSignNameByTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.GetSignNameByTokenResponse> BusinessCore.PassportServiceReference.PassportWebServiceSoap.GetSignNameByTokenAsync(BusinessCore.PassportServiceReference.GetSignNameByTokenRequest request) {
            return base.Channel.GetSignNameByTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessCore.PassportServiceReference.GetSignNameByTokenResponse> GetSignNameByTokenAsync(string token) {
            BusinessCore.PassportServiceReference.GetSignNameByTokenRequest inValue = new BusinessCore.PassportServiceReference.GetSignNameByTokenRequest();
            inValue.Body = new BusinessCore.PassportServiceReference.GetSignNameByTokenRequestBody();
            inValue.Body.token = token;
            return ((BusinessCore.PassportServiceReference.PassportWebServiceSoap)(this)).GetSignNameByTokenAsync(inValue);
        }
        
        public int CountCacheMember() {
            return base.Channel.CountCacheMember();
        }
        
        public System.Threading.Tasks.Task<int> CountCacheMemberAsync() {
            return base.Channel.CountCacheMemberAsync();
        }
    }
}
