//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTOA.PassportWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Passport.com/", ConfigurationName="PassportWebServiceReference.PassportWebServiceSoap")]
    public interface PassportWebServiceSoap {
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/HelloWorld", ReplyAction="*")]
        CTOA.PassportWebServiceReference.HelloWorldResponse HelloWorld(CTOA.PassportWebServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.HelloWorldResponse> HelloWorldAsync(CTOA.PassportWebServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 GetTokenResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetToken", ReplyAction="*")]
        CTOA.PassportWebServiceReference.GetTokenResponse GetToken(CTOA.PassportWebServiceReference.GetTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetToken", ReplyAction="*")]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.GetTokenResponse> GetTokenAsync(CTOA.PassportWebServiceReference.GetTokenRequest request);
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/ValidateToken", ReplyAction="*")]
        CTOA.PassportWebServiceReference.ValidateTokenResponse ValidateToken(CTOA.PassportWebServiceReference.ValidateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/ValidateToken", ReplyAction="*")]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.ValidateTokenResponse> ValidateTokenAsync(CTOA.PassportWebServiceReference.ValidateTokenRequest request);
        
        // CODEGEN: 命名空间 http://www.Passport.com/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetSignNameByToken", ReplyAction="*")]
        CTOA.PassportWebServiceReference.GetSignNameByTokenResponse GetSignNameByToken(CTOA.PassportWebServiceReference.GetSignNameByTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/GetSignNameByToken", ReplyAction="*")]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.GetSignNameByTokenResponse> GetSignNameByTokenAsync(CTOA.PassportWebServiceReference.GetSignNameByTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/CountCacheMember", ReplyAction="*")]
        int CountCacheMember();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Passport.com/CountCacheMember", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CountCacheMemberAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CTOA.PassportWebServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CTOA.PassportWebServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.GetTokenRequestBody Body;
        
        public GetTokenRequest() {
        }
        
        public GetTokenRequest(CTOA.PassportWebServiceReference.GetTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTokenRequestBody {
        
        public GetTokenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.GetTokenResponseBody Body;
        
        public GetTokenResponse() {
        }
        
        public GetTokenResponse(CTOA.PassportWebServiceReference.GetTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class GetTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenResult;
        
        public GetTokenResponseBody() {
        }
        
        public GetTokenResponseBody(string GetTokenResult) {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateToken", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.ValidateTokenRequestBody Body;
        
        public ValidateTokenRequest() {
        }
        
        public ValidateTokenRequest(CTOA.PassportWebServiceReference.ValidateTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class ValidateTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public ValidateTokenRequestBody() {
        }
        
        public ValidateTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateTokenResponse", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.ValidateTokenResponseBody Body;
        
        public ValidateTokenResponse() {
        }
        
        public ValidateTokenResponse(CTOA.PassportWebServiceReference.ValidateTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class ValidateTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateTokenResult;
        
        public ValidateTokenResponseBody() {
        }
        
        public ValidateTokenResponseBody(bool ValidateTokenResult) {
            this.ValidateTokenResult = ValidateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignNameByTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSignNameByToken", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.GetSignNameByTokenRequestBody Body;
        
        public GetSignNameByTokenRequest() {
        }
        
        public GetSignNameByTokenRequest(CTOA.PassportWebServiceReference.GetSignNameByTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class GetSignNameByTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetSignNameByTokenRequestBody() {
        }
        
        public GetSignNameByTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignNameByTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSignNameByTokenResponse", Namespace="http://www.Passport.com/", Order=0)]
        public CTOA.PassportWebServiceReference.GetSignNameByTokenResponseBody Body;
        
        public GetSignNameByTokenResponse() {
        }
        
        public GetSignNameByTokenResponse(CTOA.PassportWebServiceReference.GetSignNameByTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.Passport.com/")]
    public partial class GetSignNameByTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSignNameByTokenResult;
        
        public GetSignNameByTokenResponseBody() {
        }
        
        public GetSignNameByTokenResponseBody(string GetSignNameByTokenResult) {
            this.GetSignNameByTokenResult = GetSignNameByTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PassportWebServiceSoapChannel : CTOA.PassportWebServiceReference.PassportWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassportWebServiceSoapClient : System.ServiceModel.ClientBase<CTOA.PassportWebServiceReference.PassportWebServiceSoap>, CTOA.PassportWebServiceReference.PassportWebServiceSoap {
        
        public PassportWebServiceSoapClient() {
        }
        
        public PassportWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassportWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTOA.PassportWebServiceReference.HelloWorldResponse CTOA.PassportWebServiceReference.PassportWebServiceSoap.HelloWorld(CTOA.PassportWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CTOA.PassportWebServiceReference.HelloWorldRequest inValue = new CTOA.PassportWebServiceReference.HelloWorldRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.HelloWorldRequestBody();
            CTOA.PassportWebServiceReference.HelloWorldResponse retVal = ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.HelloWorldResponse> CTOA.PassportWebServiceReference.PassportWebServiceSoap.HelloWorldAsync(CTOA.PassportWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.HelloWorldResponse> HelloWorldAsync() {
            CTOA.PassportWebServiceReference.HelloWorldRequest inValue = new CTOA.PassportWebServiceReference.HelloWorldRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.HelloWorldRequestBody();
            return ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTOA.PassportWebServiceReference.GetTokenResponse CTOA.PassportWebServiceReference.PassportWebServiceSoap.GetToken(CTOA.PassportWebServiceReference.GetTokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public string GetToken() {
            CTOA.PassportWebServiceReference.GetTokenRequest inValue = new CTOA.PassportWebServiceReference.GetTokenRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.GetTokenRequestBody();
            CTOA.PassportWebServiceReference.GetTokenResponse retVal = ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).GetToken(inValue);
            return retVal.Body.GetTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.GetTokenResponse> CTOA.PassportWebServiceReference.PassportWebServiceSoap.GetTokenAsync(CTOA.PassportWebServiceReference.GetTokenRequest request) {
            return base.Channel.GetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.GetTokenResponse> GetTokenAsync() {
            CTOA.PassportWebServiceReference.GetTokenRequest inValue = new CTOA.PassportWebServiceReference.GetTokenRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.GetTokenRequestBody();
            return ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).GetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTOA.PassportWebServiceReference.ValidateTokenResponse CTOA.PassportWebServiceReference.PassportWebServiceSoap.ValidateToken(CTOA.PassportWebServiceReference.ValidateTokenRequest request) {
            return base.Channel.ValidateToken(request);
        }
        
        public bool ValidateToken(string token) {
            CTOA.PassportWebServiceReference.ValidateTokenRequest inValue = new CTOA.PassportWebServiceReference.ValidateTokenRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.ValidateTokenRequestBody();
            inValue.Body.token = token;
            CTOA.PassportWebServiceReference.ValidateTokenResponse retVal = ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).ValidateToken(inValue);
            return retVal.Body.ValidateTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.ValidateTokenResponse> CTOA.PassportWebServiceReference.PassportWebServiceSoap.ValidateTokenAsync(CTOA.PassportWebServiceReference.ValidateTokenRequest request) {
            return base.Channel.ValidateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.ValidateTokenResponse> ValidateTokenAsync(string token) {
            CTOA.PassportWebServiceReference.ValidateTokenRequest inValue = new CTOA.PassportWebServiceReference.ValidateTokenRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.ValidateTokenRequestBody();
            inValue.Body.token = token;
            return ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).ValidateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTOA.PassportWebServiceReference.GetSignNameByTokenResponse CTOA.PassportWebServiceReference.PassportWebServiceSoap.GetSignNameByToken(CTOA.PassportWebServiceReference.GetSignNameByTokenRequest request) {
            return base.Channel.GetSignNameByToken(request);
        }
        
        public string GetSignNameByToken(string token) {
            CTOA.PassportWebServiceReference.GetSignNameByTokenRequest inValue = new CTOA.PassportWebServiceReference.GetSignNameByTokenRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.GetSignNameByTokenRequestBody();
            inValue.Body.token = token;
            CTOA.PassportWebServiceReference.GetSignNameByTokenResponse retVal = ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).GetSignNameByToken(inValue);
            return retVal.Body.GetSignNameByTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.GetSignNameByTokenResponse> CTOA.PassportWebServiceReference.PassportWebServiceSoap.GetSignNameByTokenAsync(CTOA.PassportWebServiceReference.GetSignNameByTokenRequest request) {
            return base.Channel.GetSignNameByTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CTOA.PassportWebServiceReference.GetSignNameByTokenResponse> GetSignNameByTokenAsync(string token) {
            CTOA.PassportWebServiceReference.GetSignNameByTokenRequest inValue = new CTOA.PassportWebServiceReference.GetSignNameByTokenRequest();
            inValue.Body = new CTOA.PassportWebServiceReference.GetSignNameByTokenRequestBody();
            inValue.Body.token = token;
            return ((CTOA.PassportWebServiceReference.PassportWebServiceSoap)(this)).GetSignNameByTokenAsync(inValue);
        }
        
        public int CountCacheMember() {
            return base.Channel.CountCacheMember();
        }
        
        public System.Threading.Tasks.Task<int> CountCacheMemberAsync() {
            return base.Channel.CountCacheMemberAsync();
        }
    }
}
